# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6648a7834f1f38db69b8f344cf4f89d155cf35dd4a75ae08ffd1df448ce24e92b5fd758c3191d3e9d537b1a587885dd0a837694fb70387e93b4cc9c06fe9daed

test:
  secret_key_base: 5cece189394a016fbc526e5582ffb7ea316cb9e14f015e07a05ce18cdafb576690f3a07bb57468dbcb010cb98a3a718c84a82837ac5ce5a4bbd76b692a8dca6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
